CREATE TABLESPACE PRACTICASBBDD DATAFILE 'C:\app\alumno\product\21c\oradata\XE\practicasbbdd.dbf' SIZE 1024M;

ALTER SESSION 
  SET  "_ORACLE_SCRIPT"=TRUE;

CREATE USER PRACTICAS IDENTIFIED BY PRACTICASBBDD DEFAULT TABLESPACE PRACTICASBBDD TEMPORARY TABLESPACE temp; 

GRANT CONNECT TO PRACTICAS;
GRANT ACCESS TO PRACTICAS;

CREATE TABLE TABLA1 (
    CODIGO VARCHAR2 (4 BYTE) CONSTRAINT PK_CODIGO PRIMARY KEY,
    NOMBRE VARCHAR2 (20 BYTE),
    PRECIO NUMBER  CHECK (PRECIO>= 20 AND PRECIO<=120),
    PROVEEDOR VARCHAR2(5 BYTE) REFERENCES TABLA2(PK_CODIGOP) ON DELETE CASCADE,
    FECH_INI_VENTA DATE CHECK (TO_CHAR(FECHA_INI_VENTA) >12/12/2018)
);

CREATE TABLE TABLA2 (
    CODIGO_P VARCHAR2 (5 BYTE) CONSTRAINT PK_CODIGOP PRIMARY KEY,
    NOMBRE VARCHAR2(20 BYTE),
    DIRECCION VARCHAR2(25 BYTE),
    DESCUENTOS NUMBER CHECK (DESCUENTOS=1 OR DESCUENTOS=0)
);
--   1. probando las restricciones insertando
INSERT INTO TABLA1(codigo,nombre,precio,proveedor,fech_ini_venta)VALUES(1234,'prueba',140,'aaa','12/12/2018');
INSERT INTO TABLA2(codigo_p,nombre,direccion,descuentos)VALUES(12345,'prueba2','avenidaprueba',0);
INSERT INTO TABLA1(codigo,nombre,precio,proveedor,fech_ini_venta)VALUES(1234,'prueba2',20,'bbb','04/11/2011');
INSERT INTO TABLA2(codigo_p,nombre,direccion,descuentos)VALUES(12345,'prueba3','avenidaprueba',0);
--   2. ninguna restriccion funciona correctamente y al intentar arreglarlo y
--    modificar las tablas después de borrarlas todo se ha desajustado 
SELECT * FROM TABLA1;
SELECT * FROM TABLA2;
DESC TABLA1;
DESC TABLA2;
DROP TABLE TABLA1;
DROP TABLE TABLA2;

